### ISSUE TITLE
mathematical omicron makes it loopy

### ISSUE THREAD

**Issue by unhammer** [apertium/lttoolbox#127]
https://github.com/apertium/apertium/issues/151
```
$ lttoolbox/lt-comp lr tests/data/minimal-mono.dix bin
j@standard 9 10
main@standard 7 9

$ printf '%s' '𝜊' | lttoolbox/lt-proc bin
�
$ printf '%s.' '𝜊' | lttoolbox/lt-proc bin |head -c200
������������������������������������������������������������������
```

**Comment by unhammer** [comment]
```
𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊𝜊^C
Program received signal SIGINT, Interrupt.
std::less<int>::operator() (this=0x555555d921c0, __x=@0x555555d98110: 107, __y=@0x7fffffffce9c: 120586) at /usr/include/c++/10/bits/stl_function.h:386
386           { return __x < __y; }
(gdb) bt
#0  std::less<int>::operator() (this=0x555555d921c0, __x=@0x555555d98110: 107, __y=@0x7fffffffce9c: 120586) at /usr/include/c++/10/bits/stl_function.h:386
#1  0x00007ffff7d70f78 in std::_Rb_tree<int, std::pair<int const, Dest>, std::_Select1st<std::pair<int const, Dest> >, std::less<int>, std::allocator<std::pair<int const, Dest> > >::_M_lower_bound (this=0x555555d921c0, __x=0x555555d980f0, __y=0x555555d921c8, __k=@0x7fffffffce9c: 120586) at /usr/include/c++/10/bits/stl_tree.h:1935
#2  0x00007ffff7d8081a in std::_Rb_tree<int, std::pair<int const, Dest>, std::_Select1st<std::pair<int const, Dest> >, std::less<int>, std::allocator<std::pair<int const, Dest> > >::find (this=0x555555d921c0, __k=@0x7fffffffce9c: 120586) at /usr/include/c++/10/bits/stl_tree.h:2553
#3  0x00007ffff7d7f051 in std::map<int, Dest, std::less<int>, std::allocator<std::pair<int const, Dest> > >::find (this=0x555555d921c0, __x=@0x7fffffffce9c: 120586)
    at /usr/include/c++/10/bits/stl_map.h:1170
#4  0x00007ffff7d7a456 in State::apply_into (this=0x7fffffffd010, new_state=0x7fffffffcf30, input=120586, index=1, dirty=false) at state.cc:103
#5  0x00007ffff7d7a9ef in State::apply (this=0x7fffffffd010, input=120586) at state.cc:162
#6  0x00007ffff7d7b6f2 in State::step (this=0x7fffffffd010, input=120586) at state.cc:355
#7  0x00007ffff7d7b9cd in State::step_case (this=0x7fffffffd010, val=120586, caseSensitive=false) at state.cc:418
#8  0x00007ffff7d597fe in FSTProcessor::analysis (this=0x7fffffffd240, input=..., output=0x555555db8000) at fst_processor.cc:1234
#9  0x000055555555eca5 in main (argc=2, argv=0x7fffffffd768) at lt_proc.cc:406

```
