### ISSUE TITLE
Fedora test fail with LC_ALL=C.utf8

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/lttoolbox#30]
If `export LC_ALL=C.utf8` then `make test` fails with:

````
runTest (lt_print.NonWeightedFst) ... FAIL

======================================================================
FAIL: runTest (lt_print.NonWeightedFst)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/lttoolbox/tests/printtest.py", line 62, in runTest
    self.assertEqual(self.communicateFlush(), self.expectedOutput)
AssertionError: u'0\t1\tv\tv\t0.000000\t\n1\t2\ti\ti\t0.000000\t\n2\t3\th\th\t0.000000\t\n3\t4\t [truncated]... != u'0\t1\tv\tv\t0.000000\t\n1\t2\ti\ti\t0.000000\t\n2\t3\th\th\t0.000000\t\n3\t4\t [truncated]...
  0     1       v       v       0.000000
  1     2       i       i       0.000000
  2     3       h       h       0.000000
  3     4       k       k       0.000000
  4     5       i       i       0.000000
  5     6       <KEPT>  <KEPT>  0.000000
- 6     10      \u03b5  \u03b5  8238976959774720.000000
+ 6     10      \u03b5  \u03b5  0.000000
  6     7       <MATCHSOFAR>    <MATCHSOFAR>    0.000000
  7     8       <STILLMATCHING> <STILLMATCHING> 0.000000
  8     9       <NONMATCHL>     <NONMATCHR>     0.000000
- 9     10      \u03b5  \u03b5  8238976959774720.000000
+ 9     10      \u03b5  \u03b5  0.000000
  10    0.000000
````

If `export LC_ALL=en_US.utf8` then it passes. How the hell locale has an influence on weights, I don't yet know.

(Also, if `LC_ALL` is not a UTF-8 locale then all weight tests fail because they use Unicode characters - but that's expected.)

**Comment by TinoDidriksen** [comment]
OpenSUSE also fails, but with:
````
Traceback (most recent call last):
  File "tests/printtest.py", line 62, in runTest
    self.assertEqual(self.communicateFlush(), self.expectedOutput)
AssertionError: u'0\t1\tv\tv\t0.000000\t\n1\t2\ti\ti\t0.000000\t\n2\t3\th\th\t0.000000\t\n3\t4\t [truncated]... != u'0\t1\tv\tv\t0.000000\t\n1\t2\ti\ti\t0.000000\t\n2\t3\th\th\t0.000000\t\n3\t4\t [truncated]...
  0	1	v	v	0.000000	
  1	2	i	i	0.000000	
  2	3	h	h	0.000000	
  3	4	k	k	0.000000	
  4	5	i	i	0.000000	
  5	6	<KEPT>	<KEPT>	0.000000	
- 6	10	\u03b5	\u03b5	-0.000000	
?          -
+ 6	10	\u03b5	\u03b5	0.000000	
  6	7	<MATCHSOFAR>	<MATCHSOFAR>	0.000000	
  7	8	<STILLMATCHING>	<STILLMATCHING>	0.000000	
  8	9	<NONMATCHL>	<NONMATCHR>	0.000000	
- 9	10	\u03b5	\u03b5	-0.000000	
?          -
+ 9	10	\u03b5	\u03b5	0.000000	
  10	0.000000
````

The same rows showing a difference, but in this case `-0 != 0` ... even though they should actually compare equal, which `diff` doesn't know.

**Comment by TinoDidriksen** [comment]
It's `lt-comp` that effects the difference. The compiled binary differs depending on locale, even though both locales are UTF-8.

**Comment by TinoDidriksen** [comment]
For locale `C.utf8`, `lt-comp` marks the FST as having weights, even when none are present. This doesn't happen for `en_US.utf8`.
